services:
  - type: web
    name: Med-AI-Gen-AI
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn wsgi:application
      --bind 0.0.0.0:$PORT
      --workers 1
      --threads 2
      --timeout 120
      --log-level debug
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false